# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AleksaB98.ExplorerVideoPreview
PackageVersion: 1.0.1
MinimumOSVersion: 10.0.22000.0
InstallerType: inno
Scope: user
UpgradeBehavior: install
ProductCode: '{6F3B2C9E-5A41-4D7B-9E2A-8C1D4F7A3B52}_is1'
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AleksaB98/ExplorerVideoPreview/releases/download/v1.0.1/ExplorerVideoPreview-Setup.exe
  InstallerSha256: F122E92A24D0BFA1C3A8391ABB760A05A4717995A9B9431A28A1D4910765D2F8
ManifestType: installer
ManifestVersion: 1.12.0
